# Generated by Django 3.2.5 on 2021-07-29 09:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blog',
        ),
    ]
